// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System;

class P002EvenFibonacciNumbers {
  private static int sum = 0;
  private static int maxValue = 4000000;

  public static void Main() {
    int iterator = 0;
    int sequenceValue = 0;

    while (sequenceValue < maxValue) {
      sequenceValue = fib(iterator);
      if (sequenceValue % 2 == 0) {
        sum = sum + sequenceValue;
      }
      iterator++;
    }
    Console.WriteLine("The sum of the even-valued Fibonacci terms that do not exceed four million, is {0}.", sum);
  }

  public static int fib(int number) {
    if (number == 0) {
      return 0;
    }
    else if (number == 1) {
      return 1;
    }
    return fib(number - 1) + fib(number - 2);
  }
}
